// models/Trash.js
import { DataTypes } from 'sequelize';
import sequelize from '../db.js';

const Trash = sequelize.define('Trash', {
  _id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
  Transaction_Id: { type: DataTypes.STRING },
  introTransactionId: { type: DataTypes.STRING },
  bankId: { type: DataTypes.STRING },
  websiteId: { type: DataTypes.STRING },
  introUserId: { type: DataTypes.STRING },
  transactionID: { type: DataTypes.STRING },
  transactionType: { type: DataTypes.STRING },
  amount: { type: DataTypes.INTEGER },
  paymentMethod: { type: DataTypes.STRING },
  userId: { type: DataTypes.STRING },
  userName: { type: DataTypes.STRING },
  requestedUserName: { type: DataTypes.STRING },
  subAdminId: { type: DataTypes.STRING },
  subAdminName: { type: DataTypes.STRING },
  depositAmount: { type: DataTypes.INTEGER },
  withdrawAmount: { type: DataTypes.INTEGER },
  bonus: { type: DataTypes.INTEGER },
  bankCharges: { type: DataTypes.INTEGER },
  remarks: { type: DataTypes.STRING },
  bankName: { type: DataTypes.STRING },
  websiteName: { type: DataTypes.STRING },
  accountHolderName: { type: DataTypes.STRING },
  accountNumber: { type: DataTypes.BIGINT },
  ifscCode: { type: DataTypes.STRING },
  upiId: { type: DataTypes.STRING },
  upiAppName: { type: DataTypes.STRING },
  upiNumber: { type: DataTypes.STRING },
  createdAt: { type: DataTypes.DATE },
  message: { type: DataTypes.STRING },
  type: { type: DataTypes.STRING },
  nameType: { type: DataTypes.STRING },
  changedFields: { type: DataTypes.JSON },
  originalData: { type: DataTypes.JSON },
  isSubmit: { type: DataTypes.BOOLEAN },
  isApproved: { type: DataTypes.BOOLEAN },
  introducerUserName: { type: DataTypes.STRING },
  websiteTransactionId: { type: DataTypes.STRING },
  bankTransactionId: { type: DataTypes.STRING },
});

export default Trash;
